# core/trait_sampler.py
"""
Latent-trait + response-style sampler for silicon sampling.

Target population (this study): **married Iranian women, 25-45 years old**,
answering a marital-satisfaction / dyadic-adjustment / attachment questionnaire.

Each synthetic respondent's standing on six relationship latent traits is drawn
from a continuous multivariate-normal distribution with a literature-plausible
correlation structure, generated by a simple 3-factor model:

    theta_dim = L[dim] . f  +  u_dim * e_dim ,     f ~ N(0, I_3), e ~ N(0, 1)

which yields standardized traits whose covariance is  Sigma = L L' + diag(u^2)
with unit variances — guaranteed positive-semidefinite by construction, no
numpy/Cholesky needed.

Common factors:
    f[0] = R    : relationship security / positive dyadic bond
    f[1] = AVO  : attachment-avoidance proneness
    f[2] = AX   : attachment-anxiety proneness

Each respondent also gets response-STYLE parameters (acquiescence, extreme vs.
midpoint tendency, carelessness) so the eventual answers carry realistic METHOD
VARIANCE and measurement error rather than being a deterministic function of the
trait — the single biggest reason LLM survey data shows inflated Cronbach's
alpha and over-clean correlation matrices.

Pure standard library. Seedable for reproducibility.
"""

from __future__ import annotations

import math
import random
from typing import Dict, List


# ---------------------------------------------------------------------------
# Latent dimensions and their loadings on the three common factors.
# Order of factor loadings: (R_relationship, AVO_avoidance, AX_anxiety)
# Sign of a loading encodes direction; attachment_avoidance loads POSITIVELY on
# AVO and negatively on R (avoidant people report a weaker bond); attachment_anxiety
# loads POSITIVELY on AX and weakly negatively on R + partner-responsiveness
# (anxious respondents feel less responded-to). Sum of squared loadings must stay
# < 1 so uniqueness u > 0.
# ---------------------------------------------------------------------------

LOADINGS: Dict[str, tuple] = {
    "marital_satisfaction":    (0.75, -0.30, -0.15),  # overall happiness + consensus
    "dyadic_cohesion":         (0.65, -0.35, -0.10),  # shared time + affection
    "partner_responsiveness":  (0.60, -0.20, -0.30),  # feeling understood/supported
    "relationship_commitment": (0.55, -0.15,  0.10),  # effort + hope (anxiety ↑ clingy commitment)
    "attachment_avoidance":    (-0.30, 0.70,  0.05),  # discomfort with closeness
    "attachment_anxiety":      (-0.15, 0.05,  0.75),  # fear of abandonment
}

# Human-readable Persian band labels for prose rendering.
BAND_LABELS = [
    "خیلی پایین", "پایین", "کمی پایین", "متوسط", "کمی بالا", "بالا", "خیلی بالا",
]
# z-score cut points between the 7 bands.
BAND_CUTS = [-1.5, -0.9, -0.35, 0.35, 0.9, 1.5]

# Persian labels for each latent dimension (rendered into the persona / answer prompts).
DIM_LABELS_FA: Dict[str, str] = {
    "marital_satisfaction":    "رضایت و توافق زناشویی (خوشبختی کلی، توافق در امور، افکار طلاق)",
    "dyadic_cohesion":         "انسجام زناشویی و ابراز محبت (وقت‌گذرانی مشترک، خنده، صمیمیت)",
    "attachment_anxiety":      "اضطراب دلبستگی (ترس از طرد، نگرانی از دوست‌داشته‌نشده)",
    "attachment_avoidance":    "اجتناب دلبستگی (ناراحتی از صمیمیت، دشواری اعتماد)",
    "partner_responsiveness":  "پاسخگویی ادراک‌شده همسر (درک‌شدن، حمایت، توجه)",
    "relationship_commitment": "تعهد به رابطه (تلاش برای موفقیت ازدواج، امید به آینده)",
}


def format_profile_fa(profile: Dict, dims: List[str] | None = None) -> str:
    """Render a respondent's demographics + the requested latent-trait bands as a readable Persian block."""
    dims = dims or list(LOADINGS.keys())
    d = profile["demographics"]
    lines = [
        f"دموگرافیک: {d['gender']}، {d['age']} ساله، {d['education_level']}، شغل {d['occupation']}، "
        f"{d['children_count']} فرزند، {d['years_married']} سال سابقه زندگی مشترک",
        f"منطقه: {d['region']} | دینداری: {d['religiosity']} | خانوار: {d['household']} | "
        f"وضعیت اقتصادی: {d['economic_situation']}",
        f"مشکل روانشناختی (اضطراب/افسردگی با دارو): {d['psych_problem']}",
        "سطح صفات (روی طیف ۷‌بَندی از «خیلی پایین» تا «خیلی بالا»):",
    ]
    bands = profile["latent_traits_band"]
    for dim in dims:
        lines.append(f"  - {DIM_LABELS_FA.get(dim, dim)}: {bands[dim]}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Demographic sampling frame — married Iranian women 25-45.
# EDIT these to match your real recruitment frame (national statistics, your
# sample, etc.). Getting the frame right is one of the cheapest ways to raise
# external validity. All respondents are forced FEMALE and within 25-45.
# ---------------------------------------------------------------------------

# Education distribution (Iranian women 25+; married urban women skew somewhat higher).
EDUCATION_FRAME = [
    ("زیر دیپلم", 0.18),
    ("دیپلم", 0.30),
    ("فوق دیپلم / کاردانی", 0.16),
    ("کارشناسی", 0.22),
    ("کارشناسی ارشد", 0.10),
    ("دکتری / پزشکی", 0.04),
]

# Occupation distribution (housewives are a large share of married Iranian women).
OCCUPATION_FRAME = [
    ("خانه‌دار", 0.42),
    ("کارمند اداری", 0.12),
    ("معلم / کارمند آموزش", 0.09),
    ("کادر درمان (پرستار/ماما)", 0.05),
    ("دانشجو", 0.05),
    ("آرایشگر / خدمات زیبایی", 0.06),
    ("خیاط / صنایع دستی", 0.03),
    ("فروشنده / مشاغل آزاد کوچک", 0.06),
    ("مهندس / کارشناس فنی", 0.05),
    ("صاحب کسب‌وکار / کارآفرین", 0.04),
    ("استاد دانشگاه / پژوهشگر", 0.02),
    ("بیکار / جویای کار", 0.04),
]

# Region / settlement frame (broad Iranian regions + a small rural/small-town share).
REGION_FRAME = [
    ("تهران", 0.22),
    ("مرکز (اصفهان/شیراز/یزد/البرز)", 0.20),
    ("شمال (گیلان/مازندران/گلستان)", 0.10),
    ("شمال‌غرب (آذربایجان)", 0.12),
    ("غرب (کرمانشاه/همدان/لرستان/کردستان)", 0.09),
    ("جنوب (خوزستان/بوشهر/هرمزگان)", 0.09),
    ("شرق (خراسان/سیستان‌وبلوچستان)", 0.12),
    ("روستا / شهر کوچک", 0.06),
]

# Religiosity spectrum (from very religious to secular).
RELIGIOSITY_FRAME = [
    ("بسی متدین", 0.20),
    ("متعبد", 0.28),
    ("متعدل", 0.30),
    ("کم‌دین / سکولار", 0.22),
]

# Household / living arrangement.
HOUSEHOLD_FRAME = [
    ("مستقل (خانواده هسته‌ای)", 0.62),
    ("همراه با خانواده همسر", 0.20),
    ("همراه با خانواده خود", 0.10),
    ("سایر", 0.08),
]

# Perceived economic situation.
ECONOMIC_FRAME = [
    ("تنگ‌دست", 0.22),
    ("متوسط رو به پایین", 0.30),
    ("متوسط", 0.30),
    ("نسبتاً خوب", 0.13),
    ("خوب", 0.05),
]


def _band(z: float) -> str:
    idx = 0
    for cut in BAND_CUTS:
        if z >= cut:
            idx += 1
    return BAND_LABELS[idx]


def _weighted_choice(rng: random.Random, items: List[tuple]):
    r = rng.random()
    cum = 0.0
    for label, w in items:
        cum += w
        if r <= cum:
            return label
    return items[-1][0]


def _sigmoid(x: float) -> float:
    if x >= 0:
        z = math.exp(-x)
        return 1.0 / (1.0 + z)
    z = math.exp(x)
    return z / (1.0 + z)


def sample_respondent(rng: random.Random, index: int) -> Dict:
    """Draw one synthetic respondent: latent traits + response style + demographics."""
    # --- common factors ---
    r_factor = rng.gauss(0, 1)   # relationship security
    avo = rng.gauss(0, 1)        # avoidance proneness
    ax = rng.gauss(0, 1)         # anxiety proneness
    f = (r_factor, avo, ax)

    traits_z: Dict[str, float] = {}
    traits_band: Dict[str, str] = {}
    for dim, load in LOADINGS.items():
        ssq = sum(l * l for l in load)
        u = math.sqrt(max(1e-6, 1.0 - ssq))
        z = sum(l * fi for l, fi in zip(load, f)) + u * rng.gauss(0, 1)
        traits_z[dim] = round(z, 3)
        traits_band[dim] = _band(z)

    # --- response styles (method variance) ---
    response_style = {
        # >0 leans agree/high regardless of content; <0 leans disagree/low
        "acquiescence": round(rng.gauss(0, 0.40), 3),
        # >0 prefers the extreme categories; <0 hugs the midpoint
        "extreme_response": round(rng.gauss(0, 0.40), 3),
        # rare inattentive responder (near-random / straightlining)
        "careless": rng.random() < 0.04,
    }

    # --- demographics: ALL female, 25-45, currently married ---
    age = rng.randint(25, 45)
    gender = "زن"
    education = _weighted_choice(rng, EDUCATION_FRAME)
    occupation = _weighted_choice(rng, OCCUPATION_FRAME)
    region = _weighted_choice(rng, REGION_FRAME)
    religiosity = _weighted_choice(rng, RELIGIOSITY_FRAME)
    household = _weighted_choice(rng, HOUSEHOLD_FRAME)
    economic = _weighted_choice(rng, ECONOMIC_FRAME)

    # Years of marriage: plausible marriage age ~ N(22, 2.8), clipped to a sane
    # window and never younger than 16; must leave >=1 year of marriage.
    marriage_age = int(round(min(max(16, rng.gauss(22, 2.8)), min(age - 1, 29))))
    years_married = max(1, age - marriage_age)

    # Number of children, conditioned on years married (keeps it plausible).
    if years_married <= 2:
        child_frame = [(0, 0.45), (1, 0.35), (2, 0.15), (3, 0.05)]
    elif years_married <= 6:
        child_frame = [(0, 0.20), (1, 0.35), (2, 0.30), (3, 0.12), (4, 0.03)]
    else:
        child_frame = [(0, 0.10), (1, 0.22), (2, 0.34), (3, 0.20), (4, 0.10), (5, 0.04)]
    children_count = _weighted_choice(rng, child_frame)

    # Psychological-problem disclosure (anxiety/depression under medication):
    # trait-informed — high attachment anxiety and low marital satisfaction raise it.
    p = 0.10 + 0.20 * _sigmoid(traits_z["attachment_anxiety"]) + 0.10 * _sigmoid(-traits_z["marital_satisfaction"])
    p = max(0.03, min(0.50, p))
    psych_problem = "دارم" if rng.random() < p else "ندارم"

    return {
        "id": f"persona_{index}",
        "latent_traits_z": traits_z,
        "latent_traits_band": traits_band,
        "response_style": response_style,
        "demographics": {
            "gender": gender,
            "age": age,
            "education_level": education,
            "occupation": occupation,
            "children_count": children_count,
            "years_married": years_married,
            "psych_problem": psych_problem,
            "region": region,
            "religiosity": religiosity,
            "household": household,
            "economic_situation": economic,
        },
    }


def sample_population(n: int, seed: int | None = None) -> List[Dict]:
    """Draw n synthetic respondents."""
    rng = random.Random(seed)
    return [sample_respondent(rng, i + 1) for i in range(n)]


# ---------------------------------------------------------------------------
# Self-test / demo:  python -m core.trait_sampler 2000
# Prints empirical correlations to confirm the intended structure emerges.
# ---------------------------------------------------------------------------

def _corr(xs: List[float], ys: List[float]) -> float:
    n = len(xs)
    mx = sum(xs) / n
    my = sum(ys) / n
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    sxx = sum((x - mx) ** 2 for x in xs)
    syy = sum((y - my) ** 2 for y in ys)
    return sxy / math.sqrt(sxx * syy) if sxx and syy else 0.0


if __name__ == "__main__":
    import sys

    n = int(sys.argv[1]) if len(sys.argv) > 1 else 2000
    pop = sample_population(n, seed=42)

    dims = list(LOADINGS.keys())
    cols = {d: [p["latent_traits_z"][d] for p in pop] for d in dims}

    print(f"Sampled {n} married Iranian women. Empirical correlations (vs design):\n")
    checks = [
        ("marital_satisfaction", "dyadic_cohesion", "pos"),
        ("marital_satisfaction", "attachment_avoidance", "neg"),
        ("marital_satisfaction", "relationship_commitment", "pos"),
        ("partner_responsiveness", "attachment_anxiety", "neg"),
        ("dyadic_cohesion", "partner_responsiveness", "pos"),
        ("attachment_avoidance", "attachment_anxiety", "~0"),
    ]
    for a, b, expect in checks:
        r = _corr(cols[a], cols[b])
        print(f"  r({a}, {b}) = {r:+.2f}   [expected {expect}]")

    print("\nExample respondent:")
    ex = pop[0]
    print(f"  id: {ex['id']}")
    print(f"  demographics: {ex['demographics']}")
    print(f"  response_style: {ex['response_style']}")
    for d in dims:
        print(f"    {d:24s} z={ex['latent_traits_z'][d]:+.2f}  ({ex['latent_traits_band'][d]})")