# core/trait_sampler.py
"""
Latent-trait + response-style sampler for silicon sampling.

Instead of forcing personas into a handful of equal-sized categories (which
produces an unrealistic multi-modal latent distribution and bakes the
cross-construct correlations into the persona text — i.e. circularity), we
draw each synthetic respondent's standing on every latent dimension from a
continuous multivariate-normal distribution with a literature-plausible
correlation structure.

The correlation structure is generated by a simple 3-factor model:

    theta_dim = L[dim] . f  +  u_dim * e_dim ,     f ~ N(0, I_3), e ~ N(0, 1)

which yields standardized traits whose covariance is  Sigma = L L' + diag(u^2)
with unit variances — guaranteed positive-semidefinite by construction, no
numpy/Cholesky needed.

Common factors:
    f[0] = G    : general adjustment / efficacy
    f[1] = ACAD : academic self-regulation
    f[2] = EI   : emotional-intelligence

Each respondent also gets response-STYLE parameters (acquiescence, extreme vs.
midpoint tendency, carelessness) so that the eventual answers carry realistic
method variance and measurement error rather than being a deterministic
function of the trait — the single biggest reason LLM survey data shows
inflated Cronbach's alpha and over-clean correlation matrices.

Pure standard library. Seedable for reproducibility.
"""

from __future__ import annotations

import math
import random
from typing import Dict, List


# ---------------------------------------------------------------------------
# Latent dimensions and their loadings on the three common factors.
# Order of factor loadings: (G_general, ACAD_academic, EI_emotional)
# Sign of a loading encodes direction; test_anxiety loads NEGATIVELY on all
# three (anxious respondents are lower-adjustment, less organized, regulate
# worse). Sum of squared loadings must stay < 1 so uniqueness u > 0.
# ---------------------------------------------------------------------------

LOADINGS: Dict[str, tuple] = {
    # general self-efficacy (Sherer GSE)
    "self_efficacy":          (0.70,  0.10,  0.20),
    # academic self-regulation / study organization
    "study_organization":     (0.45,  0.55,  0.05),
    # test anxiety  (reverse pole of adjustment)
    "test_anxiety":           (-0.55, -0.25, -0.30),
    # academic motivation
    "academic_motivation":    (0.40,  0.60,  0.05),
    # exam-specific self-efficacy / outcome expectancy
    "exam_self_efficacy":     (0.60,  0.45,  0.10),
    # internal (effort) vs external (luck) attribution
    "internal_attribution":   (0.45,  0.30,  0.10),
    # EI: self-awareness
    "ei_self_awareness":      (0.35,  0.05,  0.65),
    # EI: understanding others' emotions
    "ei_understanding_others": (0.25,  0.00,  0.70),
    # EI: emotion regulation under stress
    "ei_emotion_regulation":  (0.50,  0.10,  0.55),
    # EI: social skills
    "ei_social_skills":       (0.30,  0.05,  0.60),
}

# Human-readable Persian band labels for prose rendering.
BAND_LABELS = [
    "خیلی پایین", "پایین", "کمی پایین", "متوسط", "کمی بالا", "بالا", "خیلی بالا",
]
# z-score cut points between the 7 bands.
BAND_CUTS = [-1.5, -0.9, -0.35, 0.35, 0.9, 1.5]

# Persian labels for each latent dimension (used when rendering profiles to text).
DIM_LABELS_FA: Dict[str, str] = {
    "self_efficacy":           "خودکارآمدی عمومی (اعتماد به انجام کارها، پشتکار)",
    "study_organization":      "سازمان‌دهی و برنامه‌ریزی مطالعه",
    "test_anxiety":            "اضطراب امتحان",
    "academic_motivation":     "انگیزش تحصیلی",
    "exam_self_efficacy":      "خودکارآمدی امتحان (اطمینان از موفقیت)",
    "internal_attribution":    "اِسناد درونی نتیجه (تلاش در برابر شانس)",
    "ei_self_awareness":       "خودآگاهی هیجانی",
    "ei_understanding_others": "درک هیجان دیگران",
    "ei_emotion_regulation":   "تنظیم هیجان در شرایط فشار",
    "ei_social_skills":        "مهارت اجتماعی",
}


def format_profile_fa(profile: Dict, dims: List[str] | None = None) -> str:
    """Render a respondent's demographics + latent-trait bands as a readable Persian block."""
    dims = dims or list(LOADINGS.keys())
    d = profile["demographics"]
    bands = profile["latent_traits_band"]
    lines = [
        f"دموگرافیک: {d['gender']}، {d['age']} ساله، {d['education_level']}، رشته {d['major']}",
        "سطح صفات (روی طیف ۷‌بَندی از «خیلی پایین» تا «خیلی بالا»):",
    ]
    for dim in dims:
        lines.append(f"  - {DIM_LABELS_FA.get(dim, dim)}: {bands[dim]}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Demographic sampling frame.  EDIT these to match your real target frame
# (e.g. national statistics or your recruitment population).  Getting the
# frame right is one of the cheapest ways to raise external validity.
# ---------------------------------------------------------------------------

EDUCATION_FRAME = [
    ("کارشناسی", 0.50),
    ("کارشناسی ارشد", 0.35),
    ("دکتری", 0.15),
]

# plausible age window per education level (min, max)
AGE_BY_EDUCATION = {
    "کارشناسی": (18, 24),
    "کارشناسی ارشد": (23, 29),
    "دکتری": (27, 35),
}

MAJORS = [
    "مهندسی کامپیوتر", "مهندسی برق", "مهندسی مکانیک", "مهندسی عمران",
    "روان‌شناسی", "علوم تربیتی", "مدیریت", "حسابداری", "اقتصاد", "حقوق",
    "پزشکی", "پرستاری", "زیست‌شناسی", "شیمی", "ریاضی", "فیزیک",
    "ادبیات فارسی", "زبان انگلیسی", "جامعه‌شناسی", "علوم سیاسی",
    "معماری", "هنر", "تربیت بدنی", "کشاورزی",
]


def _band(z: float) -> str:
    idx = 0
    for cut in BAND_CUTS:
        if z >= cut:
            idx += 1
    return BAND_LABELS[idx]


def _weighted_choice(rng: random.Random, items: List[tuple]) -> str:
    r = rng.random()
    cum = 0.0
    for label, w in items:
        cum += w
        if r <= cum:
            return label
    return items[-1][0]


def sample_respondent(rng: random.Random, index: int) -> Dict:
    """Draw one synthetic respondent: latent traits + response style + demographics."""
    # --- common factors ---
    g = rng.gauss(0, 1)
    acad = rng.gauss(0, 1)
    ei = rng.gauss(0, 1)
    f = (g, acad, ei)

    traits_z: Dict[str, float] = {}
    traits_band: Dict[str, str] = {}
    for dim, load in LOADINGS.items():
        ssq = sum(l * l for l in load)
        u = math.sqrt(max(1e-6, 1.0 - ssq))
        z = sum(l * fi for l, fi in zip(load, f)) + u * rng.gauss(0, 1)
        traits_z[dim] = round(z, 3)
        traits_band[dim] = _band(z)

    # --- response styles (method variance) ---
    response_style = {
        # >0 leans agree/high regardless of content; <0 leans disagree/low
        "acquiescence": round(rng.gauss(0, 0.40), 3),
        # >0 prefers the extreme categories; <0 hugs the midpoint
        "extreme_response": round(rng.gauss(0, 0.40), 3),
        # rare inattentive responder (near-random / straightlining)
        "careless": rng.random() < 0.04,
    }

    # --- demographics ---
    education = _weighted_choice(rng, EDUCATION_FRAME)
    lo, hi = AGE_BY_EDUCATION[education]
    age = rng.randint(lo, hi)
    gender = rng.choice(["مرد", "زن"])
    major = rng.choice(MAJORS)

    return {
        "id": f"persona_{index}",
        "latent_traits_z": traits_z,
        "latent_traits_band": traits_band,
        "response_style": response_style,
        "demographics": {
            "age": age,
            "gender": gender,
            "education_level": education,
            "major": major,
        },
    }


def sample_population(n: int, seed: int | None = None) -> List[Dict]:
    """Draw n synthetic respondents."""
    rng = random.Random(seed)
    return [sample_respondent(rng, i + 1) for i in range(n)]


# ---------------------------------------------------------------------------
# Self-test / demo:  python -m core.trait_sampler 2000
# Prints empirical correlations to confirm the intended structure emerges.
# ---------------------------------------------------------------------------

def _corr(xs: List[float], ys: List[float]) -> float:
    n = len(xs)
    mx = sum(xs) / n
    my = sum(ys) / n
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    sxx = sum((x - mx) ** 2 for x in xs)
    syy = sum((y - my) ** 2 for y in ys)
    return sxy / math.sqrt(sxx * syy) if sxx and syy else 0.0


if __name__ == "__main__":
    import sys

    n = int(sys.argv[1]) if len(sys.argv) > 1 else 2000
    pop = sample_population(n, seed=42)

    dims = list(LOADINGS.keys())
    cols = {d: [p["latent_traits_z"][d] for p in pop] for d in dims}

    print(f"Sampled {n} respondents. Empirical correlations (should match design):\n")
    checks = [
        ("self_efficacy", "test_anxiety", "neg"),
        ("self_efficacy", "exam_self_efficacy", "pos"),
        ("test_anxiety", "ei_emotion_regulation", "neg"),
        ("ei_self_awareness", "ei_understanding_others", "pos"),
        ("study_organization", "academic_motivation", "pos"),
        ("self_efficacy", "ei_social_skills", "pos"),
    ]
    for a, b, expect in checks:
        r = _corr(cols[a], cols[b])
        print(f"  r({a}, {b}) = {r:+.2f}   [expected {expect}]")

    print("\nExample respondent:")
    ex = pop[0]
    print(f"  id: {ex['id']}  |  {ex['demographics']}")
    print(f"  response_style: {ex['response_style']}")
    for d in dims:
        print(f"    {d:24s} z={ex['latent_traits_z'][d]:+.2f}  ({ex['latent_traits_band'][d]})")
