# core/trait_sampler.py
"""
Latent-trait + response-style sampler for silicon sampling.

Target population (this study): **Iranian working women, 20-40 years old,
employed in organizational/workplace settings (not self-employed, freelance,
or homemaker)**, answering a job-satisfaction / work-family-conflict /
perceived-organizational-support questionnaire.

Each synthetic respondent's standing on five workplace latent traits is drawn
from a continuous multivariate-normal distribution with a literature-plausible
correlation structure, generated by a simple 3-factor model:

    theta_dim = L[dim] . f  +  u_dim * e_dim ,     f ~ N(0, I_3), e ~ N(0, 1)

which yields standardized traits whose covariance is  Sigma = L L' + diag(u^2)
with unit variances — guaranteed positive-semidefinite by construction, no
numpy/Cholesky needed.

Common factors:
    f[0] = GWP : general workplace positivity (positive job perception, good
                 relations, felt organizational support)
    f[1] = WFC : work-family conflict proneness (both work→family and
                 family→work strain load here)
    f[2] = REL : relational/support specificity (distinguishes workplace
                 relations & perceived support from pure job satisfaction)

Each respondent also gets response-STYLE parameters (acquiescence, extreme vs.
midpoint tendency, carelessness) so the eventual answers carry realistic METHOD
VARIANCE and measurement error rather than being a deterministic function of the
trait — the single biggest reason LLM survey data shows inflated Cronbach's
alpha and over-clean correlation matrices.

Pure standard library. Seedable for reproducibility.
"""

from __future__ import annotations

import math
import random
from typing import Dict, List


# ---------------------------------------------------------------------------
# Latent dimensions and their loadings on the three common factors.
# Order of factor loadings: (GWP_workplace_positivity, WFC_conflict_proneness,
# REL_relational_support_specificity)
# Sign of a loading encodes direction: the two work-family-conflict traits load
# POSITIVELY on WFC and weakly negatively on GWP (conflict erodes workplace
# positivity); job satisfaction, workplace relations and perceived org support
# load POSITIVELY on GWP; relations and support additionally load on REL so they
# are distinguished from pure job satisfaction. Sum of squared loadings must
# stay < 1 so uniqueness u > 0.
# ---------------------------------------------------------------------------

LOADINGS: Dict[str, tuple] = {
    "job_satisfaction":                ( 0.70, -0.15,  0.10),  # pay, promotion, responsibility, eval
    "workplace_relations":             ( 0.60, -0.10,  0.55),  # coworkers, supervisors, management support
    "perceived_organizational_support": ( 0.55, -0.20,  0.55),  # org valuation, care, recognition
    "work_to_family_conflict":         (-0.20,  0.75,  0.05),  # work demands strain family life
    "family_to_work_conflict":         (-0.15,  0.70,  0.05),  # family demands strain work duties
}

# Human-readable Persian band labels for prose rendering.
BAND_LABELS = [
    "خیلی پایین", "پایین", "کمی پایین", "متوسط", "کمی بالا", "بالا", "خیلی بالا",
]
# z-score cut points between the 7 bands.
BAND_CUTS = [-1.5, -0.9, -0.35, 0.35, 0.9, 1.5]

# Persian labels for each latent dimension (rendered into the persona / answer prompts).
# These labels MUST stay aligned with instrument.CONSTRUCT_TRAIT_DIMS trait keys.
DIM_LABELS_FA: Dict[str, str] = {
    "job_satisfaction":                "رضایت شغلی (خشنودی کلی، حقوق، ترفیع، مسئولیت، ارزیابی عملکرد)",
    "workplace_relations":             "روابط شغلی (همکاران، سرپرستان، اعتماد، حمایت مدیریت)",
    "work_to_family_conflict":         "تضاد کار-خانواده (فشار شغلی مزاحم زندگی خانوادگی)",
    "family_to_work_conflict":         "تضاد خانواده-کار (مسائل خانوادگی مزاحم وظایف شغلی)",
    "perceived_organizational_support": "حمایت ادراک‌شده سازمان (قدردانی، توجه، رفاه)",
}


def format_profile_fa(profile: Dict, dims: List[str] | None = None) -> str:
    """Render a respondent's demographics + the requested latent-trait bands as a readable Persian block."""
    dims = dims or list(LOADINGS.keys())
    d = profile["demographics"]
    lines = [
        f"دموگرافیک: {d['gender']}، {d['age']} ساله، {d['education_level']}، "
        f"شغل {d['occupation']} در بخش {d['sector']} با {d['tenure']} سال سابقه کار",
        f"وضعیت اقتصادی: {d['economic_situation']}",
        "سطح صفات (روی طیف ۷‌بَندی از «خیلی پایین» تا «خیلی بالا»):",
    ]
    bands = profile["latent_traits_band"]
    for dim in dims:
        lines.append(f"  - {DIM_LABELS_FA.get(dim, dim)}: {bands[dim]}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Demographic sampling frame — Iranian working women 20-40 in organizational jobs.
# EDIT these to match your real recruitment frame. All respondents are forced
# FEMALE, aged 20-40, and hold an organizational/employee job (NOT self-employed,
# freelance, homemaker, or independent). No city/region is specified per the
# study design.
# ---------------------------------------------------------------------------

# Education distribution (working women 20-40 skew toward completed tertiary).
EDUCATION_FRAME = [
    ("دیپلم", 0.15),
    ("فوق دیپلم / کاردانی", 0.18),
    ("کارشناسی", 0.35),
    ("کارشناسی ارشد", 0.22),
    ("دکتری / پزشکی", 0.10),
]

# Occupation distribution — organizational/employee roles ONLY (no خانه‌دار,
# no freelance/self-employed/independent work, no unemployed).
OCCUPATION_FRAME = [
    ("کارمند اداری", 0.20),
    ("کارشناس / کارشناس ارشد سازمان", 0.18),
    ("معلم / کارمند آموزش", 0.15),
    ("پرستار / ماما / کادر درمان", 0.10),
    ("کارشناس فنی / مهندس سازمان", 0.10),
    ("مدیر / سرپرست اداری", 0.08),
    ("حسابدار / کارمند مالی", 0.07),
    ("پشتیبان مشتریان / اپراتور", 0.05),
    ("استاد دانشگاه / پژوهشگر", 0.04),
    ("نیروی خدمات اداری", 0.03),
]

# Employment sector.
SECTOR_FRAME = [
    ("دولتی / عمومی", 0.55),
    ("خصوصی", 0.40),
    ("تعاونی / NGO", 0.05),
]

# Tenure (years in current organizational job) — plausible for a 20-40 workforce.
TENURE_FRAME = [
    (1, 0.25), (2, 0.20), (3, 0.15), (5, 0.15), (8, 0.10), (12, 0.10), (18, 0.05),
]

# Perceived economic situation.
ECONOMIC_FRAME = [
    ("تنگ‌دست", 0.22),
    ("متوسط رو به پایین", 0.30),
    ("متوسط", 0.30),
    ("نسبتاً خوب", 0.13),
    ("خوب", 0.05),
]


def _band(z: float) -> str:
    idx = 0
    for cut in BAND_CUTS:
        if z >= cut:
            idx += 1
    return BAND_LABELS[idx]


def _weighted_choice(rng: random.Random, items: List[tuple]):
    r = rng.random()
    cum = 0.0
    for label, w in items:
        cum += w
        if r <= cum:
            return label
    return items[-1][0]


def _sigmoid(x: float) -> float:
    if x >= 0:
        z = math.exp(-x)
        return 1.0 / (1.0 + z)
    z = math.exp(x)
    return z / (1.0 + z)


def sample_respondent(rng: random.Random, index: int) -> Dict:
    """Draw one synthetic respondent: latent traits + response style + demographics."""
    # --- common factors ---
    gwp = rng.gauss(0, 1)   # general workplace positivity
    wfc = rng.gauss(0, 1)   # work-family conflict proneness
    rel = rng.gauss(0, 1)   # relational/support specificity
    f = (gwp, wfc, rel)

    traits_z: Dict[str, float] = {}
    traits_band: Dict[str, str] = {}
    for dim, load in LOADINGS.items():
        ssq = sum(l * l for l in load)
        u = math.sqrt(max(1e-6, 1.0 - ssq))
        z = sum(l * fi for l, fi in zip(load, f)) + u * rng.gauss(0, 1)
        traits_z[dim] = round(z, 3)
        traits_band[dim] = _band(z)

    # --- response styles (method variance) ---
    response_style = {
        # >0 leans agree/high regardless of content; <0 leans disagree/low
        "acquiescence": round(rng.gauss(0, 0.40), 3),
        # >0 prefers the extreme categories; <0 hugs the midpoint
        "extreme_response": round(rng.gauss(0, 0.40), 3),
        # rare inattentive responder (near-random / straightlining)
        "careless": rng.random() < 0.04,
    }

    # --- demographics: ALL female, 20-40, organizational/employee job ---
    age = rng.randint(20, 40)
    gender = "زن"
    education = _weighted_choice(rng, EDUCATION_FRAME)
    occupation = _weighted_choice(rng, OCCUPATION_FRAME)
    sector = _weighted_choice(rng, SECTOR_FRAME)
    tenure = _weighted_choice(rng, TENURE_FRAME)
    economic = _weighted_choice(rng, ECONOMIC_FRAME)

    return {
        "id": f"persona_{index}",
        "latent_traits_z": traits_z,
        "latent_traits_band": traits_band,
        "response_style": response_style,
        "demographics": {
            "gender": gender,
            "age": age,
            "education_level": education,
            "occupation": occupation,
            "sector": sector,
            "tenure": tenure,
            "economic_situation": economic,
        },
    }


def sample_population(n: int, seed: int | None = None) -> List[Dict]:
    """Draw n synthetic respondents."""
    rng = random.Random(seed)
    return [sample_respondent(rng, i + 1) for i in range(n)]


# ---------------------------------------------------------------------------
# Self-test / demo:  python -m core.trait_sampler 2000
# Prints empirical correlations to confirm the intended structure emerges.
# ---------------------------------------------------------------------------

def _corr(xs: List[float], ys: List[float]) -> float:
    n = len(xs)
    mx = sum(xs) / n
    my = sum(ys) / n
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    sxx = sum((x - mx) ** 2 for x in xs)
    syy = sum((y - my) ** 2 for y in ys)
    return sxy / math.sqrt(sxx * syy) if sxx and syy else 0.0


if __name__ == "__main__":
    import sys

    n = int(sys.argv[1]) if len(sys.argv) > 1 else 2000
    pop = sample_population(n, seed=42)

    dims = list(LOADINGS.keys())
    cols = {d: [p["latent_traits_z"][d] for p in pop] for d in dims}

    print(f"Sampled {n} Iranian working women. Empirical correlations (vs design):\n")
    checks = [
        ("job_satisfaction", "perceived_organizational_support", "pos"),
        ("job_satisfaction", "workplace_relations", "pos"),
        ("job_satisfaction", "work_to_family_conflict", "neg"),
        ("workplace_relations", "perceived_organizational_support", "pos"),
        ("work_to_family_conflict", "family_to_work_conflict", "pos"),
        ("work_to_family_conflict", "perceived_organizational_support", "neg"),
    ]
    for a, b, expect in checks:
        r = _corr(cols[a], cols[b])
        print(f"  r({a}, {b}) = {r:+.2f}   [expected {expect}]")

    print("\nExample respondent:")
    ex = pop[0]
    print(f"  id: {ex['id']}")
    print(f"  demographics: {ex['demographics']}")
    print(f"  response_style: {ex['response_style']}")
    for d in dims:
        print(f"    {d:24s} z={ex['latent_traits_z'][d]:+.2f}  ({ex['latent_traits_band'][d]})")